// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PayrollExpertApp.Data;
using System;

namespace PayrollExpertApp.Data.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PayrollExpertApp.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(70);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(70);

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(70);

                    b.Property<string>("City")
                        .HasMaxLength(70);

                    b.Property<int?>("CompanyId");

                    b.Property<string>("Country")
                        .HasMaxLength(10);

                    b.Property<int?>("PersonId");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);

                    b.Property<string>("Province")
                        .HasMaxLength(10);

                    b.Property<string>("Type")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CBABusinessNumber");

                    b.Property<string>("Contr");

                    b.Property<string>("Directors");

                    b.Property<string>("Email");

                    b.Property<bool>("MailingAddressSameAsHeadOfficeAddress");

                    b.Property<string>("Name");

                    b.Property<string>("OperatingName");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("SigningOfficer");

                    b.Property<string>("WebsiteURL");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.ShareHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CommonSharePercentage");

                    b.Property<int?>("CompanyId");

                    b.Property<string>("Name");

                    b.Property<double>("OtherPercentage");

                    b.Property<double>("PreferredSharePercentage");

                    b.Property<string>("SINNumber");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ShareHolder");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.Address", b =>
                {
                    b.HasOne("PayrollExpertApp.Data.Company")
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId");

                    b.HasOne("PayrollExpertApp.Data.Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.Person", b =>
                {
                    b.HasOne("PayrollExpertApp.Data.Company")
                        .WithMany("ContactPeople")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("PayrollExpertApp.Data.ShareHolder", b =>
                {
                    b.HasOne("PayrollExpertApp.Data.Company")
                        .WithMany("ShareHolders")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
